# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/meudb
spring.datasource.username=admin
spring.datasource.password=senha1234
spring.jpa.hibernate.ddl-auto=update

# --- MongoDB ---
spring.data.mongodb.uri=mongodb://admin:senha1234@localhost:27017/meudb?authSource=admin

# --- Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=senha1234