# Configuração da porta da aplicação
server.port=8082

# Configuração do PostgreSQL (permite rodar localmente no localhost ou no container docker postgres)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meudb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Redis (caso venha a ser utilizado com a dependência spring-boot-starter-data-redis)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:senha1234}

# Configuração do token JWT, expira em 1 hora
jwt.secret=kU4lO/5YxvCncggishpFX60V9roTn6+lkV49f7OvQGA=
jwt.expiration=3600000